import './gameRules.test';
import './uiComponents.test';
import './appConfig.test';
import './tracer.test';
import './qrCode.test';
import './simulation.test';
import './useGameState.test';
import './archive.test';
import './gamePackage.test';
